application: appthingmakeschool
version: 0-0-0
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# MAIN SCRIPT
- url: .*
  script: api.app

# LIBRARIES
libraries:
- name: webapp2
  version: "2.5.1"